### ISSUE TITLE
[BUG] DWD cannot talk to the shoot API servers anymore when APIServerSNI feature gate is enabled in g/g

### ISSUE THREAD

**Issue by rfranzke** [gardener/dependency-watchdog#22]
**Describe the bug:**
When the `APIServerSNI` feature gate is enabled in g/g then the DWD cannot talk to the kube-apiserver's anymore although they are perfectly reachable:

```
I0624 07:14:37.040182       1 prober.go:308] shoot-kube-apiserver/shoot--dev--foo/external: probe failed with error: Get https://api.foo.dev.internal.example.com/version?timeout=10s: context deadline exceeded. Will retry...
I0624 07:14:37.040244       1 prober.go:320] shoot-kube-apiserver/shoot--dev--foo/external: probe result: &scaler.probeResult{lastError:(*url.Error)(0xc0007e0540), resultRun:3}
```

This leads to the problem that the KCMs are being scaled down.
This problem resolves on its own when you restart DWD or after some time ~15-20min.

**Expected behaviour:**
DWD should continue to reach the kube-apiservers

/assign @amshuman-kr @mvladev

**Comment by rfranzke** [comment]
Any update?

**Comment by mvladev** [comment]
I think I have and idea on the root cause - when the SNI is enabled the following thing happens:

1. K8S API Server Service is changed from LoadBalancer -> ClusterIP.
1. The DNS is changed to point to the SNI LoadBalancer.

there are some problem with this - there is a TTL on the DNS record. This means that a client will request `api.foo.com` which would return the old and no longer used IP address. To workaround this I'll change the flow:

1. Check if the K8S API Server Service is of type LoadBalancer. If it's - don't modify it yet.
1. The DNS is changed to point to the SNI LoadBalancer.
1. At the end of the reconciliation, K8S API Server Service from LoadBalancer -> ClusterIP
