### ISSUE TITLE
[Feature] Enable DWD probe to delay scale up or scale down of probes dependent resources via configurable values. 

### ISSUE THREAD

**Issue by ashwani2k** [gardener/dependency-watchdog#38]
**Feature (What you would like to be added):**
Enable DWD (`Dependency Watchdog`) probe to provide mechanism to configure per resource delay for scale up or scale down operations when the external probe fails to reach the api-server. 

**Motivation (Why is this needed?):**
Currently `DWD` probe allows configuring multiple dependent resources to be scaled up or down based on availability of api-server external probe endpoint. 
This functionality is sufficient when we have only one dependent components to scale. For e.g. in current deployment only `KCM` is managed by `DWD`. 

However, we have seen in productive scenarios that just bringing down `KCM` is not sufficient as MCM (`Machine Controller Manager`) can still continue to work on the machines unchecked and can lead to undesired state of the system as described in MCM[[#679)](https://github.com/gardener/machine-controller-manager/issues/679)

As a solution to the observed issue multiple things needs to be done - 
1. We shall enhance the probe config for DWD to also scale MCM along with KCM  -- (MCM [#354](https://github.com/gardener/machine-controller-manager/issues/354#issuecomment-1028899435)
2. However just scaling MCM along with KCM is not enough as MCM needs to wait for KCM to update the Node Status before starting to reconcile the status of the machines. 
Currently the [KCM has configuration](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/) before it acts on it. 
`--node-monitor-grace-period duration     Default: 40s`
Amount of time which we allow running Node to be unresponsive before marking it unhealthy. Must be N times more than kubelet's nodeStatusUpdateFrequency, where N means number of retries allowed for kubelet to post node status.
Similarly [Kubelet has a configuration](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) 
`--node-status-update-frequency duration     Default: 10s`
Specifies how often kubelet posts node status to master.

These semantics makes it important to not just scale the resources but also induce a relevant delay to ensure that they can work on the correct state of the system. 

**Approach/Hint to the implement solution (optional):**
Ensure the solution is generic and is not coupled to only the Motivation mentioned here.

**Comment by vlerenc** [comment]
Thanks @ashwani2k. A few remarks:

> However just scaling MCM along with KCM is not enough as MCM needs to wait for KCM to update the Node Status before starting to reconcile the status of the machines.

Also KCM must wait, so that the Kubelets have enough time to update their status after the API server got responsive again. So, KCM scale-up is ideally delayed somewhat (to give the Kubelets time) and MCM's even a bit more (to give KCM time).

> Amount of time which we allow running Node to be unresponsive before marking it unhealthy. Must be N times more than kubelet's nodeStatusUpdateFrequency, where N means number of retries allowed for kubelet to post node status.

That line/consideration is more relevant for the initial time DWD waits to scale down KCM and MCM and less in the context of the scale-up later (in which context, point 2, it is mentioned), is it not? I.e. `--node-monitor-grace-period duration` influences the decision when we shut down KCM and MCM and it should be safely within that time window, so that we prevent KCM from running amok before it jumps the gun and deregister LB listener and endpoints (not a problem if the API server is down completely and it can't, but very important if only the LB or the ingress gateway has issues).
