### ISSUE TITLE
[BUG] Annotation to ignore scale-down should work for any resource

### ISSUE THREAD

**Issue by himanshu-kun** [gardener/dependency-watchdog#51]
**Describe the bug:**
Currently DWD has a feature to ignore scaling of a deployment if the annotation [`dependency-watchdog.gardener.cloud/ignore-scaling`](https://github.com/gardener/dependency-watchdog/pull/48) is added to it. It should be enhanced to more than just deployment
**Expected behaviour:**
DWD is meant to manage resources other than deployments, so annotation should work for any resource
**How To Reproduce (as minimally and precisely as possible):**

**Logs:**

**Screenshots (if applicable):**

**Anything else we need to know?**:

**Comment by unmarshall** [comment]
In principle i agree that it should be able to scale any resource. This will require additional changes and we can possibly take it up as part of the refactored codebase for DWD which is currently under implementation and testing.
Today DWD runs only in the control plane and its current scope only deals with `Deployment` and nothing else. If in future there is a need to generalise it then we can with a few changes achieve this generality.

From the perspective of priority i would categorise as a lower priority + good to have at this point in time. If you feel otherwise and you already have a use case to handle scaling of any resource that has a `scale` sub-resource then please let us know and we will increase its priority.
